node('dind-node') {
  withMaven(maven:'M3') {
    stage('Checkout') {
      git url: 'https://github.com/dcommisso/sample-spring-microservices-new.git', credentialsId: 'e86cb1fc-1970-42c1-b104-7fa94ef42947', branch: 'master'
    }
    stage('Build') {
      dir('config-service') {
        sh 'mvn clean install'
        def pom = readMavenPom file:'pom.xml'
        print pom.version
        env.version = pom.version
        currentBuild.description = "Release: ${env.version}"
      }
    }
    stage('Image') {
      dir ('config-service') {
        docker.withRegistry('https://172.17.0.1:5000') {
          def app = docker.build "piomin/config-service:${env.version}"
          app.push()
        }
      }
    }
  }
}